### ISSUE TITLE
Add Sploder.com to the list of great games that will die if flash is killed

### ISSUE THREAD

**Issue by wordigirl** [open-source-flash/open-source-flash#109]
http://www.sploder.com/
It's a really great site that helps kids make their very own games for free, and the community is golden. It would be such a shame for it to be eradicated.

**Comment by Brian151** [comment]
Ah, I haven’t really used that site for a while. Might not be quite as easy due to how sploder works. Sploder is a web site, as opposed to a simple flash application. I might look into this when I am able. I’ve already tried a few times. It’s interesting...

**Comment by Brian151** [comment]
I'm still not exactly available, but I'll try to catch back up to what I was doing soon. I still am not sure if it's going to be easy to so much as get a working copy of a single game. I've tried before. Right now, however, I need to shower and sleep. @wordigirl

**Comment by Brian151** [comment]
there still particularly much interest in this? @wordigirl 

idk when/if i'll get back to this, but...
[attached] is how far i've gotten with the physics engine data format

[sploderphys.txt](https://github.com/open-source-flash/open-source-flash/files/4877903/sploderphys.txt)

given the online component of sploder, archiving it would be difficult... 
the flash files all can be copied quite easily and the actual games are serialized to XML files, including the graphics
individual levels then are encoded with the text format as seen in the file, plus the general settings [like gravity] are applied in the XML itself. this only accounts for the physics puzzle generator. it was always by far my favorite engine to use because it was insanely flexible. 

now like i said, there's an online component here. all the data can be copied, easily... 
but i'm guessing the swfs are hard-coded to use the sploder servers/domain when accessing stuff.
so, making a working archive might not be so easy...

**Comment by wordigirl** [comment]
Thanks for your efforts. I appreciate you. 💛

**Comment by wordigirl** [comment]
Do you think there is some kind of way we can keep using flash even when browsers ban it?

**Comment by jeffythedragonslayer** [comment]
If that happens someone can always make a fork of an open source browser with the flash restrictions removed, or perhaps a plugin to allow it; I'm not sure since I've never worked on browsers before.

**Comment by Brian151** [comment]
@wordigirl 
most flash files run in the stand-alone players
MMOs and other heavily online games in theory COULD if de-coupled from the original servers.
it can be done, has in the past for fan re-launches and outright commercial piracy

@jeffythedragonslayer 
yes and no, browser dev is heavily skewed in favor of corporate software houses. there are some browsers that still support plugins [like pale moon], but generally, even the 'open source' mainstream ones all are slowly but surely phasing it out. chrome also further degrades the image of flash by running the so-called "pepper flash player" , it's known to flat-out not work on some games.

i have little time to reply now, so...later!

**Comment by jeffythedragonslayer** [comment]
Well I was hoping it would simply be a matter of finding the "disable flash" commit and undoing it out of tree lol

**Comment by Brian151** [comment]
well, kinda...
this is really starting to go beyond the original scope of this issue, but... 
disable flash will be done across a series of multiple commits, for one...
for two, the problem is not just flash player but the underlying plugin system [iirc, it's still NPAPI?]
both have to be maintained

and then there's adobe's side of things, they're dropping flash player, and open source or not : it needs to stay updated.
one of the disagreements i have with MANY people about shockwave content is that they want to continue to use the existing projectors, the existing XTRAs. this is also subject to be broken at the operating system and/or processor level some day, and it' s reasonable to assume new and more devastating exploits will be discovered/opened in the future. besides the closed-source nature of the director IDE, shockwave player/projector, and nearly every XTRA overall makes continuing to use/distribute them a fairly stickty situation to be in. we don't know everything they do for absolute fact, and there's the [unlikely] event of legal action for re-publishing them without consent. anyways, this repo ofc is about open-sourcing the flash player so it can be unofficially maintained by the fanbase as long as possible. in what form? who knows. 20 years from now, it could be integrated into some web browser, it could be a javascript framework, web assembly, who knows.

like i said, browser development is skewed in favor of mozilla/google/apple and several other large entities. most "independent" open source browsers are built off of the work of one of the already existing browser vendors. most of them do exactly the same thing, but maybe for a different OS/hardware setup. Pale Moon does try to keep support of plugins, but even they have adopted some of the not-so-welcome changes in the name of "security". it is still possible to download builds that support the unity3D plugin, though my experience in attempting that is unity is as broken as i remember it. pale moon also is in a precarious position both because they are a relatively small team and the main firefox codebase has changed so significantly that they are no longer pulling code from it. that's as i understand now. also noteworthy is that they spend a lot of time deleting code and preferences Mozilla wrote however long ago. 

now, here's the REAL kicker with maintaining a web browser: the WC3... again, run by corporations with billions of dollars. Google Chrome is receiving undeserved popularity because other browsers [including pale moon and firefox] don't actually support certain features, or certain websites and entire frameworks are deciding to use browser detection. the W3C continues to add all these new standards, the only people who can keep-up are the large corporations. and unfortunately, having a browser built just to support the flash player just isn't feasible if it can't keep-up with the modern standards as well. why? the webpages won't work...

there are just piles and piles of code and standards to keep-up with. someone will PROBABLY manage to do it, at least for the foreseeable future. but there are a lot of quite frankly, alarming technological and even political trends threatening our ability to preserve flash content [or anything, really] and the ability to run it. oh, and don't forget the security experts. they already have condemned this very repo. they want flash dead, they want flash developers to fail. [at least one had the audacity to BRAG about how his fear-mongering RUINS flash developers, and not the adobe guys building the player/IDE, the gamedevs, animators, and artists!] all they have to do is discover, exploit, disclose every single vulnerability they can find, constantly bring-up issues past and present, and that could be the end of any third-party players/browsers friendly to flash. i already have plans to leverage the asset format, and i fully expect if what i plan to do works-out, i'll have my share of critics/challenges. and i don't plan to even *touch* actionscript! flash has earned the reputation of having "more holes than swiss cheese" , you can't even shine a positive light on the file format, which is independent of the player's code, without someone bringing up "how hack-able it is". and there's the old, very outdated one about being a "proprietary black box". maybe then, between hackers and adobe, itself, flash format is extremely well documented. that's in stark contrast to unity, which regularly breaks format and code compatibility with nearly every release.

i think enough is said on this particular matter and it's best to just drop it...

**Comment by Brian151** [comment]
> 
> 
> Thanks for your efforts. I appreciate you. yellow_heart

@wordigirl 
oh, no problem
i want to preserve sploder stuff, anyways
even before flash was really starting to look doomed, i wanted to copy my games/graphics from the site because nice as the physics engine is, there are limits i don't like, and behaviors that ruin the feel of the game [like joints breaking on level end]

i however really am struggling to get even small projects done or even started as of late. i think i also need to push forward the attempts to archive anything from kongregate, since they're officially one [or more] foot in the grave... 

i also plan to hit PBS kids and neopets in the near-ish future [i actually have fiddler session archives of both] to get their flash stuff. 

it'd be slightly more feasible if not for my IRL...

also keep in mind i have the earthquake project working on cracking/decompiling shockwave. a very...interesting process, and i've been neglecting it badly...

**Comment by wordigirl** [comment]
@Brian151 I understand. Also, who were you on Sploder if you don't mind me asking? :)

**Comment by jeffythedragonslayer** [comment]
@Brian151 Wow heartbreaking stuff, but yeah we are getting out of scope lol if you have slack/discord room I would be more than happy to continue chatting on how I can help sometime.

**Comment by Brian151** [comment]
> 
> 
> @Brian151 Wow heartbreaking stuff, but yeah we are getting out of scope lol if you have slack/discord room I would be more than happy to continue chatting on how I can help sometime.

@jeffythedragonslayer 
 
well, there is a server for earthquake, still using its old name "openshockwave"
but we lack anti-spam stuff so there's no official public link... 
do you have somewhere beside github to be contacted?
also, for what would you want to help, i suppose i should ask

**Comment by Brian151** [comment]
> 
> 
> @Brian151 I understand. Also, who were you on Sploder if you don't mind me asking? :)

i would be mecaonecac
i still occasionally drop-by, actually [once to twice a year]

**Comment by jeffythedragonslayer** [comment]
Well since I've already outed myself to all the haters on this public repo, email jeff.linahan@gmail.com or telegram @jlinahan1611
If we succeed in convincing Adobe to go open source, I'd be very interested in hardening the code.  Until then I'm open to any and all suggestions. :)

**Comment by wordigirl** [comment]
Cool. My name is the same there.

**Comment by jeffythedragonslayer** [comment]
Oh, and this is more specific to your project but I really love working on physics simulations and collision detection too.

**Comment by Brian151** [comment]
@wordigirl 
i actually just decided to try that before you said so
say you're still pretty active
but i haven't checked your games yet
fun fact : i made mine when i was like 11-16-ish, i think?
now 24 and find my *own* games VERY difficult/tedious ... love it! XD

@jeffythedragonslayer 
in fact, that would be very useful... 
without de-compling the code, think you could re-build or at least design a re-build of the physics engine?
you don't actually need an account just to goof-off with it


i will do/reply more later

i might continue trying to reverse that bizarre text format soon
i'm considering with my projects starting to cycle them
my reason for having so many is i never get bored, but i still allocate weeks and months for just one at a time, and maybe i just need to not do that. i am doing this with my games i play because i have too many to give each a full and proper play session every day...

**Comment by jeffythedragonslayer** [comment]
I'll check out the feature scope of the physics puzzle maker later on sploder and let you know.  I had never heard of that site before, yesterday I was busy and tl;dr your post and thought maybe you had a SWF file you had lost the actionscript source to and needed someone to reverse engineer it.  Time to learn how to link in fortran 2018 lol XD.  Once my skill level and patience was high enough I insisted on coding everything myself: just me, a C++ compiler, and the graphics API, for maximum control... but that's not great for finding a game dev community.  Come to think of it, I haven't really had much online accountability to keep developing games for many years now... Thank you.

**Comment by Brian151** [comment]
11111#x:y#0:0#angle#0#shape;rad_x;rad_y;shape_custom_path;movement_constraints;material;strength;lock_movement;collision;passthru;sensor;fill;stroke;graphic;overlap_layer;1;scribble;events;0;0;0;0;texture_settings$

now, everything was fairly straightforward till texture_settings...

behold, a nightmare!
oy1:ci7819900y2:c2zy1:rai57798hy1:gai50006hg

this was slightly readable, rai<num> is render preset and gai<num> is geometry preset

and then i started modifying settings:
oy1:ci7819900y2:c2zy1:rai57798hy1:gai50006y5:stonei4i4zztd0.1fi5i3d0.5d0.5i7d0.5d0.5i100zd0.9268787961578363d3.5088974891158378hg

i thought the advanced texture editor was confusing, but its format manages to be even more so...

seeing how advanced texture stuff is procedural, anyways, i'll skip this for now...

next time i'll look into the physics and control components...

i also need to figure object grouping out...

**Comment by jeffythedragonslayer** [comment]
Hi Brian, so I registered as etherealdragon on sploder and played around with the physics puzzle creator.  Neat little editor.  Based on what I see in those data formats you're trying to understand, are you just looking for an API to describe the shape and physical properties of various 2D objects, and have it simulate the position and rotations at each timestep?  I did a similar physics library in Java 5 in 2010 that handled only rectangular shapes (lost the code due to HDD failure, but could rewrite it very quickly.)  I've also worked on improving and optimizing collision detection algorithms on spherical and arbitrary convex shapes in 3D:

https://arxiv.org/ftp/arxiv/papers/1211/1211.0059.pdf
https://arxiv.org/ftp/arxiv/papers/1505/1505.07873.pdf

The sploder physics puzzle creator supports concave objects, which are typically are a little bit more difficult to work with.  It looks like at least a few months of work to implement the features I see there.  I would love hear more about your project.

**Comment by Brian151** [comment]
nice name!

api/library would be ideal
having something in ...ugh... js would be nice at this current point in time since i'll be at least 'compiling' to JS for the foreseeable future. [believe me, i don't like it...] my guess is something like box2D for actual physics stuff and then custom code for the special things sploder adds. if that's feasible?

perhaps can discuss this more later as i'll be unavailable for a little while starting tomorrow

i'd imagine they are

and currently, i have no set in stone 'projects' for this, per se...
just archiving data from the site before something breaks or they decide to axe flash content like everyone else has been doing lately... also reverse-engineering the data formats, ofc... honestly, this needs more people/skills and resources than i can really provide. what really needs to be done is a full archive, and that will eat a lot of space... might need to look-into something to use web archive's "Save page" feature... i'll probably be biased towards my own games and stuff i've played/seen that i like, tbh... but i'm hoping in sharing all of what i'm doing, others might go for the bigger picture.

**Comment by jeffythedragonslayer** [comment]
I'll haven't used box2d (only bullet) but I wonder if the missing special
stuff can just be implemented in it as library features without changing too many internals, do
you have a prioritized feature request list?  :) Without more details it's difficult to say what's feasible.  It always took me quite a bit of critical thinking to properly abstract things like this without going overkill.  Also I have some experience writing a
3d mesh loader for a file format with very little documentation, mostly by
reverse engineering.

**Comment by Brian151** [comment]
@jeffythedragonslayer 
sorry for delays

i almost forgot about this thread or got sidetracked, or something...

i wonder if we should create a specific repo just for this since it'd be easier to collaborate, and we quit spamming this repo's followers with notifications every time we post a comment?

**Comment by jeffythedragonslayer** [comment]
Absolutely, send me the link.

**Comment by Brian151** [comment]
i haven't made it yet
and now deadlocking on what to name it...

**Comment by Brian151** [comment]
https://github.com/Brian151/sploded

@jeffythedragonslayer 
@wordigirl 

sorry this took so long...
hope that name works?

**Comment by jeffythedragonslayer** [comment]
Lol sure :)

**Comment by Brian151** [comment]
> 
> 
> Lol sure :)

and you're invited

**Comment by wordigirl** [comment]
Thanks! That's great

**Comment by Brian151** [comment]
> 
> 
> Thanks! That's great

and you're also invited

so, unless anything else is needing done here, i think we can close this issue?

**Comment by wordigirl** [comment]
Okay. God bless everyone and thanks for all of your help. 💛🙏
