### ISSUE TITLE
enhancement - ActionScript4 - Make Actionscript / frameworks compatible with Kotlin + Swift for cross platform development

### ISSUE THREAD

**Issue by johndpope** [open-source-flash/open-source-flash#96]
It's a far fetched idea - but if Adobe is listening - consider that 
Adobe Flash IDE (renamed to something else that's no longer relevant)
 could be resurrected to use Swift / Kotlin and piggy back off UIKit or Android native code.  

Steve Jobs killed flash -  but Apple open source swift.
so consider one way for Flash to be reborn - is to yield to swift / but make it build to android.

https://github.com/craiggrummitt/ActionSwift3/issues/2

**Comment by StefansArya** [comment]
The idea of making ActionScript4 is awesome!
I did like to improve flash as a real rival of HTML5 and be able make it cross platform with better performance. ActionScript4 will also use ECMAScript 6 or later version..

And thanks for telling me about ActionSwift3, I interested to look into it..

I was started become a programmer with ActionScript3 when I was kid because I interested with the animation..
I will never let flash die!

**Comment by ROBERT-MCDOWELL** [comment]
why not to radically change actionscript to let's say... UNISCRIPT ?
make a new language that embrace all old and new technologies like web assembly and for a long term,
just like PERL....

**Comment by zwetan** [comment]
You already have that with Adobe AIR
you can use AS3 and target iOS, Android, Windows and macOS

**Comment by ROBERT-MCDOWELL** [comment]
this git is about flash player, not AIR

**Comment by zwetan** [comment]
@ROBERT-MCDOWELL is that a joke?
it's in the title eg "...for cross platform development"

**Comment by hydroper** [comment]
@StefansArya Sad, I've used my brain hardly to design and implement a AS4 that would re-inforce the meanings and features of AS3, but no one cared for my projects.

I knew and trained ActionScript in 2014 when I was 12 and, after a bunch of experiments with HTML 5, Lua, ECMAScript, PHP, Hostinger and more, I then got stuck with transpillation and from this getting interested in transforming AS3 into a more referenced language as the spec is unclear so far. The spec has too much overview: good! ... But still incomplete.

After all my tirying work with this AS4 between 2016's Nov and 2018's middle, I decided AS3 is no benefit.

I know everything about AS3. Its grammar has Unicode-heavy identifiers and XML names, like ECMAScript, namespaces that qualify properties, verifications before evaluations etc., but also a verbose and dead grammar, ad-hoc extensions like `Vector.<E>` and badly-implemented classes like primitives (`typeof new uint is Object /*false*/`). AS3 also doubles many things from ES, so it's unworthy coming back with AS3.

I've already learnt a lot from Rust now. It's times 128 sexier and has nice immutability. I'm now just looking to translate Rust's LLVM bitcode into SWF/ABC/SWC.

**Comment by hydroper** [comment]
Read my comment and you'all will give up on ActionScript. In fact, Rust was also implemented by somo e who worked in AVM2, I heard it out.

**Comment by hydroper** [comment]
AS3 is a hell scripting language designed for crazy-landing.

**Comment by StefansArya** [comment]
I don't know you have implement AS4 somewhere. But yes, the newest adobe flash was become pretty slow because the verification before evaluating the codes.

When I was young, I have build an windows app interface with AS3 (Flash) and C++ as the backend and it just amazed my whole classroom because they've never seen animated application interface with transparent window.

The performance and memory consumption still more better rather than today's NodeJS + Electron.

But I think Adobe AIR is more better because it have cross platform support and the development still continued.

**Comment by hydroper** [comment]
@StefansArya

> I don't know you have implement AS4 somewhere. But yes, the newest adobe flash was become pretty slow because the verification before evaluating the codes.

That verification phase is easily optimisable AOT. Most verifications are ommited _ahead_-of-time, but certainly not for computations with variant types. I never read AVM2 source where it executes ABC, so I don't know, but it's probably not an issue, really.

> When I was young, I have build an windows app interface with AS3 (Flash) and C++ as the backend and it just amazed my whole classroom because they've never seen animated application interface with transparent window.

So you're saying you compiled AS3 into LLVM BC/some exec and ran it?
