### ISSUE TITLE
Adobe Community

### ISSUE THREAD

**Issue by pakastin** [open-source-flash/open-source-flash#99]
Hi all!

I got an answer from Adobe Customer Care to post the question to the Adobe Community.
https://twitter.com/AdobeCare/status/927075363431297025

Here goes: 
https://forums.adobe.com/message/9947769#9947769

🤞

**Comment by demurgos** [comment]
Great, thanks for handling this. 🙂

**Comment by ROBERT-MCDOWELL** [comment]
thansk Pakasting, keep it going!

**Comment by Brian151** [comment]
@pakastin 
awesome, and well-put on all of your points!

@ROBERT-MCDOWELL 
read your comment, and yes, this sounds accurate. Still, I'd say Adobe is a fair bit more open than others... *cough* APPLE... *cough* Just thought I'd add that. Google has grown entirely too large... Honestly, you shoulda dealt a blow to the W3C, controlled by these large firms, some of whom, IMO, shouldn't even be involved with web standards in the first place.

**Comment by Cleod9** [comment]
> Still, I'd say Adobe is a fair bit more open than others... 
@Brian151 I'm not so sure about that, I've had a bad feeling over the past year or so. Adobe has been neglecting some of the needs of AIR just as much of the Flash Player, and it makes me worry about their interest in all things relevant to Flash. Have a look at this simple thread I posted about a year ago:

https://forums.adobe.com/thread/2265270

The topic title was "Are These Forums Active?". No response. Not even an acknowledgement that the question was ever read. 

To give some context, the reason I asked this question is because I never got a response from an Adobe rep ever, anywhere, any time I asked a question. As a matter of fact, I ended up "answering" one of my own issues 6 months later after randomly noticing one particular problem went away after an AIR update:

https://forums.adobe.com/thread/2262842

What's especially sad about this is that the AIR GameInput API in particular is nearly flawless except for one blaring issue on Windows that requires a [silly OS-specific workaround](https://github.com/StackAndHeap/joystick-ane). As a result I [can't even use the .air extension](https://help.adobe.com/en_US/air/build/WS597e5dadb9cc1e0253f7d2fc1311b491071-8000.html#WS08cc5e527b086824591449d61314ebb3ae7-8000) in my app for Windows users and have to use a custom installer just because of one simple bug. Why the silence?

Anyway, what I'm getting at is that I get the feeling those forums are just a complete facade. I just don't see the connection between Adobe and the dev community...

**Comment by Brian151** [comment]
@ROBERT-MCDOWELL 
I mean in terms of the formats. True, there's a LOT they haven't published. On the other hand, there's a LOT they have. 

As far as problems with their products, yes, this is a problem, and I agree the forums don't seem particularly of use. However, the same can be said of basically everyone else. Google is egotistical, what they say is final. Apple only sees dollar signs, they do not care about much. (will give 'em credit for telling the FBI "no", though) Mirosoft's site is arcane, to say the least. They also have blatantly ignored legit complaints against them, AND tried to justify their irresponsible and inexcusable actions.

I'm not saying Adobe are innocent by any meas. Just saying, there's a lot they did share... Others really haven't.

**Comment by ROBERT-MCDOWELL** [comment]
@Brian151 and @Cleod9 
I think real open source developers must absolutely wake up before to finish free workers of these "death"poration (corpo/corpus means dead body in latin). They must wakeup and realize what the real game is in this internet technology challenges:
- U.S. corps pact are working together since the start of internet, their shitty fake competition game is only to distract people of what the common interest they are really working on.
- It never been a question of money or profit, but a question of control (that's why W3C 33 club)
- Real open source is played in one way, the way that these dead entities use the creativity and energy of all talented developers of this planet for free, but on this other way, will never release the source of google search engine algorithm, audio/video protocol (skype/ms) etc..
They need to control the internet and use open source developers as plebs to apply their whatever common agenda. How convenient to create a code racism by repeating every day that actionscript, flash is bad and html5/js is good? well, look at the result after 6 years how repetition of lies and non sense work on humans! it's outstanding..
I'm not against these corps who btw just do their job to make their dreams (ugly or not) real. This is the real game we, users/developers who created what is internet today (linux, network protocol etc)) must be aware of. This game can help our consciousness to evolve and not to be trapped as a sheep into an artificial state. It's up to us to make internet as we want, not them or any standards.

**Comment by Brian151** [comment]
seems i messed-up a mention, as well... DERP....

I think honestly the corporations have gotten so large and powerful it'll take direct governmental action to do much about them. Start by strengthening U.S. Anti-Trust, then split Google, Microsoft, etc... 

I'm not exactly unaware of these games they play. It's why I despise them in basically their entirety. My mother, on the other hand, denies how much control these scumbags actually have over the GOVERNMENT, and totally believes that most of the time, "charitable" actions are done out of the goodness of their hearts.

Way's we're better-off than tribes? let's see
healthcare- wait, Big Pharma
internet- government got involved, corporations call the shots
modern conveniences- an overwhelming percentage no one really needs or wants
unity- news : "why it's ok for you to kill your neighbor if they're different"

Yep, basically, nothing solid. Anything that would be good is spoiled by corrupt governments, the corporations, and lamestream media's propaganda pushing. The rest is just fat we need to trim.

Another problem with the standard organizations isn't the organizations, even. It's those in charge of implementing what the standards organizations even come up with. Web/Software struggles with this, especially. I wouldn't say standards organizations are inherently bad or useless, though. Rather, they get corrupted by those who have no legitimate business being there, like government. No surprise, there...

Sorry again if this is's the most coherent post, tired, just woke-up, also I've already spent too much brain energy beating this dead horse with either those who don't know or don't care, or with those who are fully aware but can do nothing about it. It gets to be exhausting, and I'd rather worry about just writing code than how what some corporation does impacts the code I write, or the program said code belongs to. (My mom genuinely believes also that the stuff corps do isn't something that impacts me, or anyone else...)

re: "death"poration
try this one: corp-"rats"
Picked this up from some guy on youtube, and it is one of my favorite insults to big corporations, particularly the scumbags. I acknowledge that maybe a handful *might* have a conscience, but most of them do not... 
Although as for the "death" thing, iirc, it also means body. I'll have to look-up what the MEANING of corporation really is.

**Comment by Cleod9** [comment]
@Brian151 Yeah, I guess Adobe has done _something_ at least, but I really just wished they'd **_talk_** to us... Give us a "yes", give us a "no", give us a "we're looking into it".  And I know what you mean by it being exhausting, most of us just want to write our code in peace. But there's a select few of us who's livelihood depends on Flash's existence, at least in terms of preservation. Web game hubs are going to start dropping like flies after losing their Flash inventory in 2020 (you can't replace 20 years of flash content with HTML5 in less than 5 years). And I feel extremely nervous about if AIR is going to be next with the way things have been going. They've publicly stated AIR development [will continue for now](https://forums.adobe.com/thread/2362234), but with the lack of support on their forums I find it hard to believe it will last much longer

@ROBERT-MCDOWELL Haha wow, i think that's the first I've heard of the term "code racism", but it sounds pretty accurate.

**Comment by ROBERT-MCDOWELL** [comment]
@Brian151 
> I think honestly the corporations have gotten so large and powerful it'll take direct governmental action to do much about them. Start by strengthening U.S. Anti-Trust, then split Google, Microsoft, etc...
how is it possible since all recommendations are coming from themselves?
the laws today are ignored and covered up with recommendations.
they even discretely modified or created laws that protects corporations against government so....
meanwhile the white card has been done among all those deathporation (this is not an insult but the real by law meaning of what is a corporation) for the so called national security interest (give me a flying break...).

> Way's we're better-off than tribes? let's see
> healthcare- wait, Big Pharma
> internet- government got involved, corporations call the shots
> modern conveniences- an overwhelming percentage no one really needs or wants
> unity- news : "why it's ok for you to kill your neighbor if they're different"
well tried, let me answer:
> healthcare- wait, Big Pharma
tribe: the nature offers everything to heal for free, thanks to our centuries gnostic knowledge
and it's free
> internet- government got involved, corporations call the shots
tribe: well, as we are the government we don't need it, to communicate with other tribes (rarely needed)
we just use our legs, smoke or animals to bring communication
and it's free
> modern conveniences- an overwhelming percentage no one really needs or wants
tribe: we are living close to a creek with absolute pure water coming from deep earth, we made a small
canal to carry the water in the middle of the village, everyone is healthy and happy to drink it.
the food is stocked in our common cellar, used in case of poor harvest
and it's free
> unity- news : "why it's ok for you to kill your neighbor if they're different"
tribe: ??? what an idea to kill your neighbor since it's there are part of the village working as a baker
and btw my son is married with his daughter....

:D next please

**Comment by pakastin** [comment]
Oh gosh, we don't get anywhere with hate. No matter how big the company, there are just **ordinary people** we need to convince. Could we please keep this conversation sane?

This is not a war, this is a good cause and preserving a piece of internet history.

**Comment by Brian151** [comment]
I will re-open and then re-close (i think i can?) this, as there was more I had to say... @pakastin 

@Cleod9 
I feel your frustration. I MIGHT have a way to get a connection, but the time to do so may well have passed. and IDK what kind of connection it is... Probably something very minor
Matt Roszak is one such dev I worry about. His games NEED Flash, and there's no way around that. 
Well, some of those hubs have dropped (mochimedia being the only one that comes to mind)
Kong and NG may survive, but it seems the increase in HTML5/webGL/Unity games has come with a massive decline in quality, and that will hurt both of them. People don't go to those for something casual or that's just like the other 1,000,000+ games. I actually read-through a discussion on Newgrounds about Unity vs Flash. I love how everyone praised Unity, which I wouldn't mind, except they didn't seem to care much to address the very real flaws that it has. Meanwhile, Flash gets the same treatment it does everywhere else. A lot of the old movies on Newgrounds also had extras (plus, used vectors extensively), and the conversion to being actual videos has dealt them a harsh blow. Likewise, the iconic web games are flash based. Heck, the iconic LEGO web games, are shockwave! Some CD-ROM games also operate under shockwave projectors, but at least those have the relevant software bundled on-disk, so they're still viable for a bit longer. Not only can you not replace that inventory in 5+ years, with the current state of affairs, you can't replace it, period. HTML5 is not viable as a replacement. Unlike Flash, it has made very little progress in relation to the time it has existed. Pretty sure Flash was doing way better when it was this old. Ofc, I didn't play Flash games back then, so I can only go by what others say or have already said.

@ROBERT-MCDOWELL 
Rather not re-address this, but basically, that sounds right, and nice examples of tribes.

@pakastin 
re "hate"
I do agree, and that's one of the reasons my example of the news saying that you can kill your neighbor was come-up with. The mask modern society wears is that it is open-minded, that people understand one another, or that they should. But... this is not the case. There are those outcast, they are bullied, they are assaulted, they are exploited, and slaughtered.... At best, society turns a blind eye. At worse, it encourages and endorses this savage behavior. You talk about hate? society is full of it. 
re "just people"
Now, these businesses, that rake in literally BILLIONS, sure, they're full of "just people"... Those just people, at least the ones with any level of "power", aren't always so innocent. Maybe they can be convinced, but it seems to take being firm/aggressive to convince them. (For example, how often a federal court order has to be used to keep Apple in-line) Even if the company truly cares, or the CEO does, there's the entire board of directors, and the shareholders to consider. It gets more complicated when working with another entity. For example, Rareware's last Nintendo game, Dinosaur Planet, or what became known as Starfox Adventures. Now, I won't jump the gun to just accuse Nintendo of abusing their authority, but... there are some real oddities with how that game was converted. The only aspects that really went-well are audio/visual. The game, itself, and especially story, something happened... Like I said, I won't point fingers, but I will state this one fact: Nintendo decides what gets published to their systems. well, officially published, anyways. That affords them some control over anyone developing for one of those systems. I also personally know individuals who HAVE been, or are being screwed-over by large corporations. And regardless of EVERYTHING else, these companies have so much money, and so many lawyers, they can actually make the laws change to benefit them, and only them. They're "just people", alright. If I were to go to congress and lobby for something, doesn't matter what it was, if I even benefited from it, I'd be turned-down. Even 100 of me would be ignored. Because I don't have a lot of money, and I really don't have much influence over future elections. The FCC recently did this. Although note that some of the members DID vote against repealing Net Neutrality, the organization as a whole ignored MULTIPLE complaints, even from businesses of ALL sizes. Why? Big Cable. The reason corporations are not treated like people, is because they don't act like people. (Well, decent ones...) Regardless of the reason, they tend to disregard ethics, morality, common sense, and even the law. Maybe they can be changed, but it's more than likely going to take at best, a Christmas Carol type of scenario, to basically emotionally blackmail them, and remind them who they used to be, who they're hurting, and that they both won't be missed when they're gone, and are probably going straight to hell for how they choose to treat others. I agree just going and making enemies is reckless, and not helpful in the long run. I respect your optimism, and trying to take the humanitarian approach. I really do. However, some of us, myself included, are not optimists. I'm about 10% optimist, 45% realist, and 45% idealist. e.g. I'm mostly pessimistic. I don't choose this, but because of my own unique experiences, this is what I am. I do really want to be able to cooperate with these companies, but I somewhat wonder if they really are willing. (or at least, if some members of them are...) They seem to be content with the way things are, they're making record profits, they're growing, they own more and more "Intellectual Property" (*shudders* i hate that word...). Why should they feel motivated to help us? Just being honest here. Now, the people that actually do the work for them? I bet they'd love to! But, those people risk losing their job and/or being sued if they step out of line. If it's serious enough, they can end-up in jail.
conclusion:
Again, sorry for bringing that up AGAIN, but really, not trying to instigate any fights here, but, at least from our own experiences, the experiences of those we know, or have heard of, the set of facts Robert and I have to go on do not paint such a wonderful picture, and there's no reason that they should. I do try to have some faith, but understand that it is limited, and you should not brush-off the reasons why. I don't want to make enemies with these companies, or the people that run them, but are they even our friends in the first place? Do they even want to be? Some of this is based on speculation, but how much does Adobe have to gain by open-sourcing Flash? The main one is it's no longer their burden. Except, wait! They then get pressure for doing that! Apple? Most likely none, they don't want Flash, they started the ball rolling to end it. Google? not sure, they can be wild and unpredictable, at times. Microsoft? Hard to say. Mozilla? They want to be like Google. W3C? as a whole, most likely not interested in this. 

With that out of the way, I was going to work on something more productive
